version: 2
sources:
    - name: datafeed
      database: "{{('test')}}"
      schema: raw_schema
      tables:
        - name: raw_customerdata
        - name: employees_raw
        - name: raw_customers
        - name: raw_products
        - name: raw_orders
          columns:
           - name: id
             tests:
               - unique
               - not_null
           - name: status
             tests:
              - accepted_values:
                 values: ['placed','shipped','completed','returned','return_pending']

        


      
